// ULTRA-MINIMAL Tailwind Configuration
// Target: <20KB total CSS bundle

/** @type {import('tailwindcss').Config} */
export default {
  mode: "jit",
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx,js,jsx}"],
  // Extremely minimal safelist
  safelist: ["__next", "dark"],
  theme: {
    // Use default theme with minimal extensions
    extend: {
      colors: {
        // Only CSS variables - no actual color values
        border: "hsl(var(--border))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          active: "hsl(var(--primary-active))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        error: {
          DEFAULT: "hsl(var(--error))",
          foreground: "hsl(var(--error-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      borderRadius: {
        lg: "var(--radius-lg)",
        md: "var(--radius-md)",
        sm: "var(--radius-sm)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        full: "var(--radius-full)",
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "Oxygen",
          "Ubuntu",
          "Cantarell",
          "Fira Sans",
          "Droid Sans",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: [
          "SF Mono",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
      fontSize: {
        xs: "var(--font-size-xs)",
        sm: "var(--font-size-sm)",
        base: "var(--font-size-base)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
        "2xl": "var(--font-size-2xl)",
        "3xl": "var(--font-size-3xl)",
        "4xl": "var(--font-size-4xl)",
        "5xl": "var(--font-size-5xl)",
      },
      lineHeight: {
        tight: "var(--line-height-tight)",
        snug: "var(--line-height-snug)",
        normal: "var(--line-height-normal)",
        relaxed: "var(--line-height-relaxed)",
        loose: "var(--line-height-loose)",
        body: "var(--line-height-body)",
      },
      letterSpacing: {
        tighter: "var(--letter-spacing-tighter)",
        tight: "var(--letter-spacing-tight)",
        normal: "var(--letter-spacing-normal)",
        wide: "var(--letter-spacing-wide)",
        wider: "var(--letter-spacing-wider)",
        widest: "var(--letter-spacing-widest)",
      },
      spacing: {
        0: "0",
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        20: "var(--space-20)",
        24: "var(--space-24)",
      },
      animation: {
        "fade-in": "fade-in var(--duration-normal) var(--ease-out)",
        "fade-in-up": "fade-in-up var(--duration-normal) var(--ease-out)",
        "fade-in-down": "fade-in-down var(--duration-normal) var(--ease-out)",
        "scale-in": "scale-in var(--duration-normal) var(--ease-out)",
        "slide-in-right": "slide-in-right var(--duration-normal) var(--ease-out)",
        "pulse": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      transitionDuration: {
        instant: "var(--duration-instant)",
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
        slower: "var(--duration-slower)",
      },
      transitionTimingFunction: {
        linear: "var(--ease-linear)",
        in: "var(--ease-in)",
        out: "var(--ease-out)",
        "in-out": "var(--ease-in-out)",
        spring: "var(--ease-spring)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        "2xl": "var(--shadow-2xl)",
        inner: "var(--shadow-inner)",
      },
      zIndex: {
        base: "var(--z-base)",
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        overlay: "var(--z-overlay)",
        modal: "var(--z-modal)",
        popover: "var(--z-popover)",
        tooltip: "var(--z-tooltip)",
        notification: "var(--z-notification)",
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            "--tw-prose-body": theme("colors.foreground"),
            "--tw-prose-headings": theme("colors.foreground"),
            "--tw-prose-lead": theme("colors.muted.foreground"),
            "--tw-prose-links": theme("colors.primary.DEFAULT"),
            "--tw-prose-bold": theme("colors.foreground"),
            "--tw-prose-counters": theme("colors.muted.foreground"),
            "--tw-prose-bullets": theme("colors.muted.foreground"),
            "--tw-prose-hr": theme("colors.border"),
            "--tw-prose-quotes": theme("colors.muted.foreground"),
            "--tw-prose-quote-borders": theme("colors.primary.DEFAULT"),
            "--tw-prose-captions": theme("colors.muted.foreground"),
            "--tw-prose-code": theme("colors.foreground"),
            "--tw-prose-pre-code": theme("colors.foreground"),
            "--tw-prose-pre-bg": theme("colors.muted.DEFAULT"),
            "--tw-prose-th-borders": theme("colors.border"),
            "--tw-prose-td-borders": theme("colors.border"),
            maxWidth: "65ch",
            fontSize: "var(--font-size-base)",
            lineHeight: "var(--line-height-relaxed)",
            a: {
              textDecorationThickness: "1px",
              textUnderlineOffset: "2px",
              transition: "all var(--duration-fast) var(--ease-out)",
              "&:hover": {
                textDecorationThickness: "2px",
              },
            },
            h1: {
              fontSize: "var(--font-size-4xl)",
              fontWeight: "var(--font-weight-black)",
              lineHeight: "var(--line-height-tight)",
              letterSpacing: "var(--letter-spacing-tighter)",
            },
            h2: {
              fontSize: "var(--font-size-2xl)",
              fontWeight: "var(--font-weight-bold)",
              lineHeight: "var(--line-height-snug)",
              letterSpacing: "var(--letter-spacing-tight)",
            },
            h3: {
              fontSize: "var(--font-size-xl)",
              fontWeight: "var(--font-weight-semibold)",
              lineHeight: "var(--line-height-snug)",
            },
            h4: {
              fontSize: "var(--font-size-lg)",
              fontWeight: "var(--font-weight-semibold)",
            },
            code: {
              fontWeight: "var(--font-weight-medium)",
            },
            blockquote: {
              fontStyle: "italic",
            },
            th: {
              fontWeight: "var(--font-weight-semibold)",
            },
          },
        },
        dark: {
          css: {
            "--tw-prose-body": theme("colors.foreground"),
            "--tw-prose-headings": theme("colors.foreground"),
            "--tw-prose-lead": theme("colors.muted.foreground"),
            "--tw-prose-links": theme("colors.primary.DEFAULT"),
            "--tw-prose-bold": theme("colors.foreground"),
            "--tw-prose-counters": theme("colors.muted.foreground"),
            "--tw-prose-bullets": theme("colors.muted.foreground"),
            "--tw-prose-hr": theme("colors.border"),
            "--tw-prose-quotes": theme("colors.muted.foreground"),
            "--tw-prose-quote-borders": theme("colors.primary.DEFAULT"),
            "--tw-prose-captions": theme("colors.muted.foreground"),
            "--tw-prose-code": theme("colors.foreground"),
            "--tw-prose-pre-code": theme("colors.foreground"),
            "--tw-prose-pre-bg": theme("colors.muted.DEFAULT"),
            "--tw-prose-th-borders": theme("colors.border"),
            "--tw-prose-td-borders": theme("colors.border"),
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
  // WHITELIST APPROACH: Only enable what we actually use
  corePlugins: {
    // Reset/Preflight
    preflight: true,

    // Layout essentials only
    display: true,
    position: true,
    inset: true,
    zIndex: true,
    overflow: true,
    visibility: true,
    boxSizing: true,
    float: true,
    clear: true,

    // Flexbox essentials
    flexDirection: true,
    flexWrap: true,
    alignItems: true,
    justifyContent: true,
    alignContent: true,
    alignSelf: true,
    flex: true,
    flexGrow: true,
    flexShrink: true,
    gap: true,

    // Grid essentials
    gridTemplateColumns: true,
    gridColumn: true,
    gridTemplateRows: true,
    gridRow: true,

    // Spacing
    padding: true,
    margin: true,
    space: true,

    // Sizing
    width: true,
    height: true,
    maxWidth: true,
    minWidth: true,
    minHeight: true,
    maxHeight: true,

    // Typography essentials
    fontSize: true,
    fontWeight: true,
    lineHeight: true,
    textAlign: true,
    textColor: true,
    textDecoration: true,
    whitespace: true,

    // Backgrounds
    backgroundColor: true,

    // Borders
    borderRadius: true,
    borderWidth: true,
    borderColor: true,
    borderStyle: true,

    // Interactivity
    cursor: true,
    pointerEvents: true,

    // Transitions
    transitionProperty: true,
    transitionDuration: true,
    transitionTimingFunction: true,

    // Transforms (basic)
    transform: true,
    scale: true,
    translate: true,

    // Opacity
    opacity: true,

    // Accessibility
    screenReaders: true,

    // Disable everything else
    isolation: false,
    objectFit: false,
    objectPosition: false,
    overscrollBehavior: false,
    container: false,
    boxDecorationBreak: false,
    tableLayout: false,
    captionSide: false,
    borderCollapse: false,
    borderSpacing: false,
    transformOrigin: false,
    rotate: false,
    skew: false,
    touchAction: false,
    scrollBehavior: false,
    scrollMargin: false,
    scrollPadding: false,
    scrollSnapAlign: false,
    scrollSnapStop: false,
    scrollSnapType: false,
    appearance: false,
    columns: false,
    breakAfter: false,
    breakBefore: false,
    breakInside: false,
    gridAutoFlow: false,
    gridAutoColumns: false,
    gridAutoRows: false,
    gridColumnStart: false,
    gridColumnEnd: false,
    gridRowStart: false,
    gridRowEnd: false,
    flexBasis: false,
    order: false,
    justifyItems: false,
    justifySelf: false,
    placeContent: false,
    placeItems: false,
    placeSelf: false,
    size: false,
    fontFamily: false,
    fontStyle: false,
    fontSmoothing: false,
    fontVariantNumeric: false,
    letterSpacing: false,
    lineClamp: false,
    listStyleImage: false,
    listStylePosition: false,
    listStyleType: false,
    textDecorationColor: false,
    textDecorationStyle: false,
    textDecorationThickness: false,
    textUnderlineOffset: false,
    textTransform: false,
    textOverflow: false,
    textWrap: false,
    textIndent: false,
    verticalAlign: false,
    wordBreak: false,
    hyphens: false,
    content: false,
    backgroundAttachment: false,
    backgroundClip: false,
    backgroundOrigin: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    backgroundImage: false,
    gradientColorStops: false,
    borderOpacity: false,
    divideColor: false,
    divideOpacity: false,
    divideStyle: false,
    divideWidth: false,
    outlineStyle: false,
    outlineWidth: false,
    outlineOffset: false,
    outlineColor: false,
    ringWidth: false,
    ringColor: false,
    ringOpacity: false,
    ringOffsetWidth: false,
    ringOffsetColor: false,
    boxShadow: false,
    boxShadowColor: false,
    mixBlendMode: false,
    backgroundBlendMode: false,
    blur: false,
    brightness: false,
    contrast: false,
    dropShadow: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
    filter: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    backdropFilter: false,
    transitionDelay: false,
    animation: false,
    caretColor: false,
    accentColor: false,
    resize: false,
    userSelect: false,
    willChange: false,
    fill: false,
    stroke: false,
    strokeWidth: false,
    aspectRatio: false,
  },
};
