// ULTRA-MINIMAL Tailwind Configuration
// Target: <20KB total CSS bundle

/** @type {import('tailwindcss').Config} */
export default {
  mode: "jit",
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx,js,jsx}"],
  // Extremely minimal safelist
  safelist: ["__next", "dark"],
  theme: {
    // Use default theme with minimal extensions
    extend: {
      colors: {
        // Only CSS variables - no actual color values
        border: "hsl(var(--border))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
      },
    },
  },
  plugins: [],
  // WHITELIST APPROACH: Only enable what we actually use
  corePlugins: {
    // Reset/Preflight
    preflight: true,

    // Layout essentials only
    display: true,
    position: true,
    inset: true,
    zIndex: true,
    overflow: true,
    visibility: true,

    // Flexbox essentials
    flexDirection: true,
    flexWrap: true,
    alignItems: true,
    justifyContent: true,
    flex: true,
    gap: true,

    // Grid essentials
    gridTemplateColumns: true,
    gridColumn: true,
    gridTemplateRows: true,
    gridRow: true,

    // Spacing
    padding: true,
    margin: true,
    space: true,

    // Sizing
    width: true,
    height: true,
    maxWidth: true,
    minHeight: true,

    // Typography essentials
    fontSize: true,
    fontWeight: true,
    lineHeight: true,
    textAlign: true,
    textColor: true,
    textDecoration: true,

    // Backgrounds
    backgroundColor: true,

    // Borders
    borderRadius: true,
    borderWidth: true,
    borderColor: true,

    // Interactivity
    cursor: true,
    pointerEvents: true,

    // Transitions
    transitionProperty: true,
    transitionDuration: true,
    transitionTimingFunction: true,

    // Transforms (basic)
    transform: true,
    scale: true,

    // Opacity
    opacity: true,

    // Accessibility
    screenReaders: true,

    // Disable everything else
    float: false,
    clear: false,
    isolation: false,
    objectFit: false,
    objectPosition: false,
    overscrollBehavior: false,
    container: false,
    boxDecorationBreak: false,
    boxSizing: false,
    tableLayout: false,
    captionSide: false,
    borderCollapse: false,
    borderSpacing: false,
    transformOrigin: false,
    translate: false,
    rotate: false,
    skew: false,
    touchAction: false,
    scrollBehavior: false,
    scrollMargin: false,
    scrollPadding: false,
    scrollSnapAlign: false,
    scrollSnapStop: false,
    scrollSnapType: false,
    appearance: false,
    columns: false,
    breakAfter: false,
    breakBefore: false,
    breakInside: false,
    gridAutoFlow: false,
    gridAutoColumns: false,
    gridAutoRows: false,
    gridColumnStart: false,
    gridColumnEnd: false,
    gridRowStart: false,
    gridRowEnd: false,
    flexBasis: false,
    flexGrow: false,
    flexShrink: false,
    order: false,
    justifyItems: false,
    justifySelf: false,
    alignContent: false,
    alignSelf: false,
    placeContent: false,
    placeItems: false,
    placeSelf: false,
    minWidth: false,
    maxHeight: false,
    size: false,
    fontFamily: false,
    fontStyle: false,
    fontSmoothing: false,
    fontVariantNumeric: false,
    letterSpacing: false,
    lineClamp: false,
    listStyleImage: false,
    listStylePosition: false,
    listStyleType: false,
    textDecorationColor: false,
    textDecorationStyle: false,
    textDecorationThickness: false,
    textUnderlineOffset: false,
    textTransform: false,
    textOverflow: false,
    textWrap: false,
    textIndent: false,
    verticalAlign: false,
    whitespace: false,
    wordBreak: false,
    hyphens: false,
    content: false,
    backgroundAttachment: false,
    backgroundClip: false,
    backgroundOrigin: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    backgroundImage: false,
    gradientColorStops: false,
    borderStyle: false,
    borderOpacity: false,
    divideColor: false,
    divideOpacity: false,
    divideStyle: false,
    divideWidth: false,
    outlineStyle: false,
    outlineWidth: false,
    outlineOffset: false,
    outlineColor: false,
    ringWidth: false,
    ringColor: false,
    ringOpacity: false,
    ringOffsetWidth: false,
    ringOffsetColor: false,
    boxShadow: false,
    boxShadowColor: false,
    mixBlendMode: false,
    backgroundBlendMode: false,
    blur: false,
    brightness: false,
    contrast: false,
    dropShadow: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
    filter: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    backdropFilter: false,
    transitionDelay: false,
    animation: false,
    caretColor: false,
    accentColor: false,
    resize: false,
    userSelect: false,
    willChange: false,
    fill: false,
    stroke: false,
    strokeWidth: false,
    aspectRatio: false,
  },
};
