import { Calendar, FileText } from 'lucide-react';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';

interface MonthlySummary {
  period: string;
  content: string;
  generatedAt: string;
  metadata: {
    model?: string;
    article_count?: number;
    ranking_change_count?: number;
    new_tool_count?: number;
    site_change_count?: number;
  };
}

async function getMonthlySummary(): Promise<MonthlySummary | null> {
  try {
    // Use relative URL for internal API calls - works in both development and production
    const response = await fetch('/api/whats-new/summary', {
      cache: 'no-store', // Always fetch fresh data
    });

    if (!response.ok) {
      console.error('Failed to fetch monthly summary:', response.status);
      return null;
    }

    const data = await response.json();
    return data.summary;
  } catch (error) {
    console.error('Error fetching monthly summary:', error);
    return null;
  }
}

export default async function WhatsNewPage() {
  const summary = await getMonthlySummary();

  if (!summary) {
    return (
      <div className="text-center py-16">
        <FileText className="h-16 w-16 mx-auto text-muted-foreground mb-4" />
        <h2 className="text-xl font-semibold mb-2">No Monthly Summary Available</h2>
        <p className="text-muted-foreground max-w-md mx-auto">
          The monthly summary will be generated automatically based on recent activity.
          Check back soon for insights into the latest AI tool rankings and platform updates.
        </p>
      </div>
    );
  }

  const periodDate = new Date(summary.period + '-01');
  const formattedPeriod = periodDate.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
  });

  const generatedDate = new Date(summary.generatedAt);
  const formattedGenerated = generatedDate.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h2 className="text-2xl font-bold mb-2">{formattedPeriod}</h2>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Calendar className="h-4 w-4" />
            <span>Generated {formattedGenerated}</span>
            {summary.metadata.article_count !== undefined && (
              <>
                <span>•</span>
                <span>{summary.metadata.article_count} articles analyzed</span>
              </>
            )}
          </div>
        </div>
        {summary.metadata.model && (
          <Badge variant="outline" className="text-xs">
            Generated by {summary.metadata.model}
          </Badge>
        )}
      </div>

      <Separator />

      {/* Summary Content */}
      <div
        className="prose prose-sm max-w-none dark:prose-invert prose-headings:font-semibold prose-a:text-primary hover:prose-a:underline prose-p:leading-relaxed prose-li:my-1"
        dangerouslySetInnerHTML={{
          __html: summary.content
            .replace(/\n\n/g, '</p><p>')
            .replace(/\n/g, '<br/>')
            .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
            .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>')
            .replace(/^(.+)$/, '<p>$1</p>'),
        }}
      />

      {/* Statistics */}
      {summary.metadata && (
        <>
          <Separator className="my-8" />
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {summary.metadata.article_count !== undefined && (
              <div className="text-center p-4 rounded-lg bg-muted/50">
                <div className="text-3xl font-bold text-primary mb-1">
                  {summary.metadata.article_count}
                </div>
                <div className="text-sm text-muted-foreground">Articles</div>
              </div>
            )}
            {summary.metadata.new_tool_count !== undefined && (
              <div className="text-center p-4 rounded-lg bg-muted/50">
                <div className="text-3xl font-bold text-primary mb-1">
                  {summary.metadata.new_tool_count}
                </div>
                <div className="text-sm text-muted-foreground">New Tools</div>
              </div>
            )}
            {summary.metadata.ranking_change_count !== undefined && (
              <div className="text-center p-4 rounded-lg bg-muted/50">
                <div className="text-3xl font-bold text-primary mb-1">
                  {summary.metadata.ranking_change_count}
                </div>
                <div className="text-sm text-muted-foreground">Ranking Updates</div>
              </div>
            )}
            {summary.metadata.site_change_count !== undefined && (
              <div className="text-center p-4 rounded-lg bg-muted/50">
                <div className="text-3xl font-bold text-primary mb-1">
                  {summary.metadata.site_change_count}
                </div>
                <div className="text-sm text-muted-foreground">Site Updates</div>
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}
