/**
 * Generate State of AI Summary (Direct Service Call)
 * Bypasses API authentication for local testing
 *
 * Usage: npx tsx scripts/generate-state-of-ai.ts [month] [year]
 */

import dotenv from "dotenv";
import { StateOfAiSummaryService } from "../lib/services/state-of-ai-summary.service";

// Load environment variables
dotenv.config({ path: ".env.local" });

async function generateStateOfAi() {
  try {
    console.log("🚀 Starting State of AI generation...\n");

    // Get month and year from command line args, or use current date
    const now = new Date();
    const month = process.argv[2] ? parseInt(process.argv[2], 10) : now.getMonth() + 1;
    const year = process.argv[3] ? parseInt(process.argv[3], 10) : now.getFullYear();

    // Validate inputs
    if (month < 1 || month > 12) {
      throw new Error("Month must be between 1 and 12");
    }

    if (year < 2020 || year > 2030) {
      throw new Error("Year must be between 2020 and 2030");
    }

    console.log(`📅 Target: ${getMonthName(month)} ${year}`);
    console.log(`👤 Generated by: cli-script\n`);

    // Create service and generate
    const service = new StateOfAiSummaryService();
    const startTime = Date.now();

    console.log("⚡ Generating State of AI editorial...");
    console.log("   (This may take 30-60 seconds)\n");

    const result = await service.generateStateOfAi(
      month,
      year,
      "cli-script",
      true // Force regenerate
    );

    const duration = Date.now() - startTime;

    console.log(`✅ Generation complete in ${duration}ms\n`);

    // Display results
    console.log("📊 Summary Details:");
    console.log(`   ID: ${result.summary.id}`);
    console.log(`   Month/Year: ${result.summary.month}/${result.summary.year}`);
    console.log(`   Generated: ${result.summary.generatedAt.toISOString()}`);
    console.log(`   Content Length: ${result.summary.content.length} chars`);
    console.log(`   Is New: ${result.isNew}`);
    console.log(`   Generation Time: ${result.generationTimeMs}ms\n`);

    // Display first 500 characters of content
    console.log("📄 Content Preview:");
    console.log("─".repeat(80));
    console.log(result.summary.content.substring(0, 500));
    if (result.summary.content.length > 500) {
      console.log("\n... (truncated, see database for full content)");
    }
    console.log("─".repeat(80));

    console.log("\n✅ State of AI editorial saved to database!");
    console.log("\n📋 Next steps:");
    console.log("   1. Verify in admin UI:");
    console.log("      → http://localhost:3007/en/admin/state-of-ai");
    console.log("   2. View on What's New page:");
    console.log("      → http://localhost:3007/en/whats-new");
    console.log("   3. Test public API:");
    console.log("      → curl http://localhost:3007/api/state-of-ai/current\n");
  } catch (error) {
    console.error("\n❌ Generation failed:");
    console.error(error instanceof Error ? error.message : "Unknown error");
    if (error instanceof Error && error.stack) {
      console.error("\nStack trace:");
      console.error(error.stack);
    }
    process.exit(1);
  }
}

function getMonthName(month: number): string {
  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];
  return months[month - 1] || "Unknown";
}

// Run generation
generateStateOfAi();
