"use client";

import {
  Archive,
  ArrowLeft,
  ArrowRight,
  Calendar,
  ChevronLeft,
  ChevronRight,
  Clock,
  Sparkles,
} from "lucide-react";
import Link from "next/link";
import ReactMarkdown from "react-markdown";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import type { Locale } from "@/i18n/config";
import type { Dictionary } from "@/i18n/get-dictionary";

interface MonthlySummary {
  id: string;
  period: string;
  periodFormatted: string;
  content: string;
  metadata: any;
  generatedAt: string;
}

interface NavigationInfo {
  previous: { period: string; title: string } | null;
  next: { period: string; title: string } | null;
}

interface WhatsNewContentProps {
  summary: MonthlySummary;
  navigation: NavigationInfo;
  dict: Dictionary;
  lang: Locale;
  isLatest: boolean;
}

export default function WhatsNewContent({
  summary,
  navigation,
  dict,
  lang,
  isLatest,
}: WhatsNewContentProps): React.JSX.Element {
  const formatDate = (dateString: string): string => {
    const date = new Date(dateString);

    if (Number.isNaN(date.getTime())) {
      return "Date unavailable";
    }

    return date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  };

  // Extract metadata stats
  const articleCount = summary.metadata?.article_count || 0;
  const toolCount = summary.metadata?.tool_count || 0;

  return (
    <div className="max-w-4xl mx-auto">
      {/* Back Button */}
      <div className="flex items-center justify-between mb-6">
        <Button variant="ghost" asChild>
          <Link href={`/${lang}/news`}>
            <ArrowLeft className="h-4 w-4 mr-2" />
            {dict.common?.back || "Back to News"}
          </Link>
        </Button>
        <Button variant="outline" asChild>
          <Link href={`/${lang}/whats-new/archive`}>
            <Archive className="h-4 w-4 mr-2" />
            View Archive
          </Link>
        </Button>
      </div>

      {/* Header Card */}
      <Card className="mb-8">
        <CardHeader>
          {/* Latest Badge */}
          {isLatest && (
            <Badge className="w-fit mb-4" variant="default">
              <Sparkles className="h-3 w-3 mr-1" />
              Latest Report
            </Badge>
          )}

          {/* Title */}
          <CardTitle className="text-3xl md:text-4xl mb-4">
            What's New in AI Coding Tools
          </CardTitle>
          <CardDescription className="text-xl">
            {summary.periodFormatted}
          </CardDescription>

          {/* Metadata */}
          <div className="flex flex-wrap items-center gap-4 mt-4 text-sm text-muted-foreground">
            <div className="flex items-center gap-1">
              <Calendar className="h-4 w-4" />
              {formatDate(summary.generatedAt)}
            </div>
            <div className="flex items-center gap-1">
              <Clock className="h-4 w-4" />
              Generated by AI
            </div>
          </div>

          {/* Stats */}
          {(articleCount > 0 || toolCount > 0) && (
            <div className="flex flex-wrap gap-2 mt-4">
              {articleCount > 0 && (
                <Badge variant="secondary">
                  {articleCount} article{articleCount !== 1 ? "s" : ""} analyzed
                </Badge>
              )}
              {toolCount > 0 && (
                <Badge variant="secondary">
                  {toolCount} tool{toolCount !== 1 ? "s" : ""} updated
                </Badge>
              )}
            </div>
          )}
        </CardHeader>

        <CardContent>
          {/* Main Content - Markdown Rendering */}
          <div className="prose prose-lg dark:prose-invert max-w-none">
            <ReactMarkdown
              components={{
                a: ({ node, ...props }) => (
                  <a
                    {...props}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-primary hover:underline"
                  />
                ),
                h1: ({ node, ...props }) => (
                  <h1 {...props} className="text-3xl font-bold mt-8 mb-4" />
                ),
                h2: ({ node, ...props }) => (
                  <h2 {...props} className="text-2xl font-semibold mt-6 mb-3" />
                ),
                h3: ({ node, ...props }) => (
                  <h3 {...props} className="text-xl font-semibold mt-4 mb-2" />
                ),
                ul: ({ node, ...props }) => (
                  <ul {...props} className="list-disc list-inside space-y-2 my-4" />
                ),
                ol: ({ node, ...props }) => (
                  <ol {...props} className="list-decimal list-inside space-y-2 my-4" />
                ),
                li: ({ node, ...props }) => <li {...props} className="ml-4" />,
                p: ({ node, ...props }) => <p {...props} className="my-4 leading-relaxed" />,
                blockquote: ({ node, ...props }) => (
                  <blockquote
                    {...props}
                    className="border-l-4 border-primary pl-4 italic my-4"
                  />
                ),
                code: ({ node, ...props }) => (
                  <code
                    {...props}
                    className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono"
                  />
                ),
              }}
            >
              {summary.content}
            </ReactMarkdown>
          </div>

          {/* Navigation to Previous/Next Months */}
          <Separator className="my-8" />
          <div className="flex flex-col sm:flex-row justify-between gap-4">
            {navigation.previous ? (
              <Button variant="outline" asChild className="flex-1">
                <Link href={`/${lang}/whats-new/${navigation.previous.period}`}>
                  <ChevronLeft className="h-4 w-4 mr-2" />
                  <div className="text-left">
                    <div className="text-xs text-muted-foreground">Previous</div>
                    <div className="text-sm font-medium">{navigation.previous.title}</div>
                  </div>
                </Link>
              </Button>
            ) : (
              <div className="flex-1" />
            )}

            {navigation.next ? (
              <Button variant="outline" asChild className="flex-1">
                <Link href={`/${lang}/whats-new/${navigation.next.period}`}>
                  <div className="text-right">
                    <div className="text-xs text-muted-foreground">Next</div>
                    <div className="text-sm font-medium">{navigation.next.title}</div>
                  </div>
                  <ChevronRight className="h-4 w-4 ml-2" />
                </Link>
              </Button>
            ) : (
              <div className="flex-1" />
            )}
          </div>

          {/* Back to Latest (only show on historical pages) */}
          {!isLatest && (
            <>
              <Separator className="my-6" />
              <Button variant="default" asChild className="w-full">
                <Link href={`/${lang}/whats-new`}>
                  <ArrowRight className="h-4 w-4 mr-2" />
                  View Latest Report
                </Link>
              </Button>
            </>
          )}
        </CardContent>
      </Card>

      {/* AI Generation Note */}
      <Card className="bg-muted/50">
        <CardContent className="pt-6">
          <p className="text-sm text-muted-foreground">
            <strong>Note:</strong> This monthly summary was generated by AI based on news
            articles, tool updates, and industry developments tracked by AI Power Rankings. The
            content is automatically curated to provide a comprehensive overview of the AI coding
            tools landscape.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
